[build]
  publish = "public"
  command = "hugo --gc --minify"
[build.environment]
  HUGO_VERSION = "0.92.2"

[context.production.environment]
  HUGO_VERSION = "0.92.2"

  [context.split1.environment]
    HUGO_ENV = "production"
